#!/usr/bin/env groovy
// the "!#/usr/bin... is just to to help IDEs, GitHub diffs, etc properly detect the language and do syntax highlighting for you.
// thx to https://github.com/jenkinsci/pipeline-examples/blob/master/docs/BEST_PRACTICES.md

def updateMasterBranch(final String repoName)
{
	echo "BEGIN updateMasterBranch with repoName=${repoName}";

	final repoURL = "git@github.com:metasfresh/${repoName}.git";
	echo "repoURL=${repoURL}";

	sh "git clone ${repoURL}";

	dir(repoName)
	{
		sh "git config user.email \"dev@metasfresh.com\"";
		sh "git config user.name \"metas.dev\"";

			sh "git config push.default matching"

			sh 'git checkout -B master'; // -B: create or reset
			sh "git pull ${repoURL} master" // just to be sure that we really have the latest master..not sure if this is neccesary

			sh 'git merge origin/release';

			sh "git remote set-url origin ${repoURL}";
			sh "git push";
	}
	echo "END updateMasterBranch with repoName=${repoName}";
}

timestamps
{
stage("Checkout repos")
{
    node('linux')
    {
		deleteDir(); // clear or workspace
		sshagent(['metas-dev-ssh-key'])
		{
			updateMasterBranch 'metasfresh-parent';
			updateMasterBranch 'metasfresh-admin';
			updateMasterBranch 'metasfresh';
			updateMasterBranch 'metasfresh-webui-api';
			updateMasterBranch 'metasfresh-webui-frontend';
			updateMasterBranch 'metasfresh-procurement-webui';
			updateMasterBranch 'metasfresh-dist';
			updateMasterBranch 'metasfresh-dist-orgs';
		}
	}
}
} // timestamps
